#!/usr/bin/env bash
# update_oui.sh - download the Wireshark manuf list and convert it to the
# shared/data/oui.txt format used by shared/oui.py.
#
# Output format: one entry per line
#   <6-hex-lowercase-prefix><TAB><Vendor Name>
#
# Only 24-bit MA-L (OUI) entries are kept; 28-bit MA-M and 36-bit MA-S
# entries (prefixes longer than 6 hex chars) are skipped.
#
# Usage:
#   bash scripts/update_oui.sh
#
# The script downloads:
#   https://www.wireshark.org/download/automated/data/manuf
#
# Mirror structure/style of scripts/update_categories.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OUT_FILE="$REPO_ROOT/shared/data/oui.txt"
TMP_FILE="$(mktemp)"

MANUF_URL="https://www.wireshark.org/download/automated/data/manuf"

echo "[update_oui] Downloading Wireshark manuf list from $MANUF_URL ..."
if command -v curl &>/dev/null; then
    curl -fsSL "$MANUF_URL" -o "$TMP_FILE"
elif command -v wget &>/dev/null; then
    wget -q "$MANUF_URL" -O "$TMP_FILE"
else
    echo "[update_oui] ERROR: neither curl nor wget found." >&2
    rm -f "$TMP_FILE"
    exit 1
fi

echo "[update_oui] Converting to oui.txt format ..."

{
    echo "# OUI vendor lookup table - generated by scripts/update_oui.sh"
    echo "# Source: $MANUF_URL"
    echo "# Format: <6-hex-lowercase-prefix><TAB><Vendor Name>"
    echo "# 24-bit MA-L entries only."
    echo ""

    # Wireshark manuf format:
    #   AA:BB:CC\tShortName\tLong Description
    # or for MA-M/MA-S:
    #   AA:BB:CC:DD/28\t...
    #
    # We want only lines where the prefix is exactly 8 chars (AA:BB:CC),
    # i.e. no slash (no MA-M/MA-S) and exactly 2 colons in the prefix part.
    awk -F'\t' '
        /^#/ { next }
        NF < 2 { next }
        {
            prefix = $1
            # Skip MA-M (28-bit) and MA-S (36-bit) - they contain a slash.
            if (index(prefix, "/") > 0) next
            # Strip colons and lowercase.
            gsub(/:/, "", prefix)
            prefix = tolower(prefix)
            # Only accept exactly 6 hex chars (24-bit OUI).
            if (length(prefix) != 6) next
            # Use the short name (field 2); if blank, use long name (field 3).
            vendor = $2
            if (vendor == "" && NF >= 3) vendor = $3
            if (vendor == "") next
            # Strip leading/trailing whitespace from vendor.
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", vendor)
            print prefix "\t" vendor
        }
    ' "$TMP_FILE"
} > "$OUT_FILE"

rm -f "$TMP_FILE"

COUNT=$(grep -c '^[0-9a-f]' "$OUT_FILE" || true)
echo "[update_oui] Done. $COUNT entries written to $OUT_FILE"
