# update_oui.ps1 - download the Wireshark manuf list and convert it to the
# shared/data/oui.txt format used by shared/oui.py.
#
# Output format: one entry per line
#   <6-hex-lowercase-prefix><TAB><Vendor Name>
#
# Only 24-bit MA-L (OUI) entries are kept; 28-bit MA-M and 36-bit MA-S
# entries (prefixes longer than 6 hex chars) are skipped.
#
# Usage (from repo root):
#   powershell -ExecutionPolicy Bypass -File scripts\update_oui.ps1

$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot   = Split-Path -Parent $ScriptDir
$OutFile    = Join-Path $RepoRoot 'shared\data\oui.txt'
$ManufUrl   = 'https://www.wireshark.org/download/automated/data/manuf'
$TmpFile    = [System.IO.Path]::GetTempFileName()

Write-Host "[update_oui] Downloading Wireshark manuf list from $ManufUrl ..."
try {
    $wc = New-Object System.Net.WebClient
    $wc.DownloadFile($ManufUrl, $TmpFile)
} catch {
    Write-Error "[update_oui] Download failed: $_"
    Remove-Item -Force $TmpFile -ErrorAction SilentlyContinue
    exit 1
}

Write-Host "[update_oui] Converting to oui.txt format ..."

$lines = [System.IO.File]::ReadAllLines($TmpFile, [System.Text.Encoding]::UTF8)
$out   = [System.Collections.Generic.List[string]]::new()

$out.Add("# OUI vendor lookup table - generated by scripts/update_oui.ps1")
$out.Add("# Source: $ManufUrl")
$out.Add("# Format: <6-hex-lowercase-prefix><TAB><Vendor Name>")
$out.Add("# 24-bit MA-L entries only.")
$out.Add("")

foreach ($line in $lines) {
    # Skip comments and blank lines.
    if ($line -match '^\s*#' -or $line.Trim() -eq '') { continue }

    $fields = $line -split "`t"
    if ($fields.Count -lt 2) { continue }

    $prefix = $fields[0].Trim()

    # Skip MA-M (28-bit) and MA-S (36-bit) entries which contain a slash.
    if ($prefix -match '/') { continue }

    # Strip colons and lowercase.
    $prefix = $prefix -replace ':', ''
    $prefix = $prefix.ToLowerInvariant()

    # Only keep exactly 6 hex chars (24-bit OUI).
    if ($prefix.Length -ne 6) { continue }
    if ($prefix -notmatch '^[0-9a-f]{6}$') { continue }

    # Use short name (field 2); fall back to long description (field 3).
    $vendor = $fields[1].Trim()
    if ($vendor -eq '' -and $fields.Count -ge 3) {
        $vendor = $fields[2].Trim()
    }
    if ($vendor -eq '') { continue }

    $out.Add("$prefix`t$vendor")
}

Remove-Item -Force $TmpFile -ErrorAction SilentlyContinue

[System.IO.File]::WriteAllLines($OutFile, $out, [System.Text.Encoding]::UTF8)

$count = ($out | Where-Object { $_ -match '^[0-9a-f]' }).Count
Write-Host "[update_oui] Done. $count entries written to $OutFile"
